### PR TITLE
feat(multiple-arbitrable-payment): split fund if there is no ruling

### PR DESCRIPTION
**Pull request by n1c01a5**

### CODE REVIEW

**Comment by n1c01a5** [comment]
the contract has 1000 (amount) + 20 (arbitration fee) * 2
but 20 are taken by the arbitrator so it's 1000 + 20 / 2 = 510 no?

**Comment by epiqueras** [comment]
Each person should get:
```
((transaction.sellerFee > transaction.buyerFee ? transaction.sellerFee : transaction.buyerFee) / 2) + transaction.amount / 2
```

**Comment by epiqueras** [comment]
But see the review for a suggestion on how to better track fees paid.

**Comment by n1c01a5** [comment]
> Each person should get:
> 
> ```
> ((transaction.sellerFee > transaction.buyerFee ? transaction.sellerFee : transaction.buyerFee) + transaction.amount) / 2
> ```

I don't think it works because I think in some cases you overpass the amount and a sending transaction (the last one in this case) can not executed

**Comment by n1c01a5** [comment]
https://github.com/kleros/kleros-interaction/pull/153

**Pull request closed without merging**
