### PR TITLE
fix(escrows): check the caller of the appeal call

### PR DESCRIPTION
**Pull request by n1c01a5**

### CODE REVIEW

**Comment by epiqueras** [comment]
Insurers won't be able to appeal if we merge this.

**Comment by n1c01a5** [comment]
yes that's the problem to fix this we need maybe a curated list of insurers

**Comment by epiqueras** [comment]
I think it’s fine as is. The grief factor is way bigger than 1. We can
close this PR.

**Comment by n1c01a5** [comment]
the grief factor is impossible to compute. It's depends the amount of the transaction, delay of the transaction, relationship between the parties. And as Ferit noted the drawback is not implemented.
(For info, this issue it not urgent).

**Comment by epiqueras** [comment]
Yeah but it grows exponentially with every appeal. And the ruling gets
exponentially more “honest” with more jurors too, so it’s not really an
issue.

**Comment by n1c01a5** [comment]
The grief factor depends on the amount of the transaction. If the amount transaction is very huge (like 1M) the arbitrator costs are negligible for several appeals.

**Comment by epiqueras** [comment]
That would be too expensive. The denominator is fixed and the numerator grows with every appeal. It's fine, it's just like the T2CR.

**Comment by n1c01a5** [comment]
for example the 1st appeal is not expenive

**Pull request closed without merging**
