### PR TITLE
fix(Linguo): Ferit's review

### PR DESCRIPTION
**Pull request by unknownunknown1**

### CODE REVIEW

**Comment by ferittuncer** [comment]
I think it would be nicer to loop for each task for `amountWithdrawable` function, just like the other one, what do you think? @unknownunknown1

**Comment by unknownunknown1** [comment]
You mean to go through the whole `Task[] public tasks` array? I'm not sure. I think it will be less informative without an option to choose a particular task.  And `withdrawFeesAndRewards` also has a taskID parameter so I think it's better to keep it here as well, since those 2 functions basically mirror each other.

**Comment by ferittuncer** [comment]
My idea in mind was: I am a user of the contract and not sure what I stand to earn from which task. So I want to query all at once.

Maybe instead of this, we can return task numbers the beneficiary is involved, so he can query for each of them. Looping for a single equality check should be good I think, in terms of gas.

**Comment by unknownunknown1** [comment]
> Maybe instead of this, we can return task numbers the beneficiary is involved

With current setup there is no easy way to get those I think. We would need to create a new mapping for this, like (address => uint[]), and manage it when money is contributed/withdrawn.
Or I could just replace taksID parameter with array, so the user can provide the IDs himself

**Comment by ferittuncer** [comment]
Can't we just loop the tasks array and return the subset where all task ids belong to beneficiary?

**Comment by unknownunknown1** [comment]
We would also need to check each round of the task to look through all contributions

**Comment by ferittuncer** [comment]
Right. So the only way is to maintain storage for this.

I would say we should implement this for ease-of-use. But it also adds a bit of complexity to the contract. Let's discuss this.

Other than that, all good, I'm merging.

**Pull request merged**
