### PR TITLE
Put myself on the reviewers list

### PR DESCRIPTION
**Pull request by unknownunknown1**

### CODE REVIEW

**Comment by epiqueras** [comment]
Because you did a strange merge and duplicated commits, please rebase stale branches instead.

**Comment by unknownunknown1** [comment]
I did something. Not sure it worked. How do I do that exactly?
I also accidentally deleted one file in the process. Can this be reverted?
I'm new to GitHub, sorry

**Comment by epiqueras** [comment]
This should help, https://git-scm.com/book/en/v2/Git-Branching-Rebasing.

**Comment by unknownunknown1** [comment]
I run command "git rebase origin" and it says "Current branch is up to date". Does it mean it's done?
Since PR still has 2 old commits I was thinking about squashing them, like it says here https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request#rebasing-code-and-cleaning-up-comments
But I'm not sure if I should do that.

**Comment by epiqueras** [comment]
No, your history is still muddy and that won't help. It's a one line change, just start from a fresh pull and make 1 commit.

**Comment by unknownunknown1** [comment]
Done. Thanks for your assistance

**Pull request closed without merging**
