### PR TITLE
test file for AppealableArbitrator.sol

### PR DESCRIPTION
**Pull request by unknownunknown1**

### CODE REVIEW

**Comment by ferittuncer** [comment]
Addressing #133

**Comment by epiqueras** [comment]
Hi, thanks for your contribution.

Can you please fix the format/linting errors. `yarn run prettify` `yarn run lint`.

**Comment by unknownunknown1** [comment]
Hi, I ran those commands. Formatting is fixed but check fails for some reason

**Comment by epiqueras** [comment]
That's just a warning. The error comes from your test throwing.

```
1 failing
  1) Contract: AppealableArbitrator
       Should get correct latest AppealID:
```

**Comment by unknownunknown1** [comment]
Fixed

**Pull request merged**
